service: wkhtmltopdf-aws-lambda-layer
provider:
  name: aws
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:AddLayerVersionPermission
        - lambda:GetLayerVersion
      Resource: "*"
layers:
  wkhtmltopdf:
    package:
      artifact: layer.zip
